version: 2
updates:
  - package-ecosystem: "docker-compose"
    directories: 
      - "/airconnect/docker-compose.yml"
      - "/pihole/docker-compose.yml"
      - "/plex/docker-compose.yml"
      - "/portainer/docker-compose.yml"
    schedule:
      interval: "weekly"
