version: '2'
services:
  plex:
    image: plexinc/pms-docker:1.43.2.10687-563d026ea
    restart: unless-stopped
    environment:
      - TZ=Canada/Eastern
      - PLEX_UID=${PLEX_UID}
      - PLEX_GID=${PLEX_GID}
    networks:
      macvlan:
        ipv4_address: ${IP_PLEX}
    hostname: plex
    volumes:
      - plex_config:/config:rw
      - plex_transcode:/transcode:rw
      - /volume1/media:/data:ro
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
networks:
  macvlan:
    external: true
volumes:
  plex_config:
  plex_transcode:
