version: '2'
services:
  pihole:
    image: pihole/pihole:2026.04.1
    restart: unless-stopped
    environment:
      TZ: Canada/Eastern
      FTLCONF_dns_revServers: ${FTLCONF_dns_revServers}
      FTLCONF_dns_upstreams: ${FTLCONF_dns_upstreams}
      FTLCONF_webserver_api_password: ${FTLCONF_webserver_api_password}
    networks:
      macvlan:
        ipv4_address: ${IP_PIHOLE}
    hostname: pihole
    cap_add:
      - NET_ADMIN
    volumes:
      - /volume1/docker/pihole/pihole:/etc/pihole:rw
networks:
  macvlan:
    external: true
