version: '2'
services:
  airconnect:
    image: 1activegeek/airconnect:latest
    restart: unless-stopped
    environment:
      - AIRCAST_VAR=-x /config/config.xml
      - AIRUPNP_VAR=kill
    network_mode: host
    volumes:
      - /volume1/docker/airconnect/config:/config
