version: '2'
services:
  agent:
    container_name: agent
    image: portainer/agent
    restart: always
    networks:
      - agent_network
    ports:
      - 9001:9001/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/@docker/volumes:/var/lib/docker/volumes

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: unless-stopped
    command: -H tcp://agent:9001 --tlsskipverify
    networks:
      - agent_network
    ports:
      - 9443:9443/tcp
      - 8000:8000/tcp
    volumes:
      - portainer_data:/data:rw
    depends_on:
      - agent

networks:
  agent_network:
    driver: bridge

volumes:
  portainer_data:
