version: '2'
services:
  agent:
    image: portainer/agent:2.39.3-alpine
    restart: always
    ports:
      - 9001:9001/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /volume1/@docker/volumes:/var/lib/docker/volumes:rw
  portainer:
    image: portainer/portainer-ce:2.39.4-alpine
    restart: unless-stopped
    command: -H tcp://agent:9001 --tlsskipverify
    ports:
      - 9443:9443/tcp
      - 8000:8000/tcp
    volumes:
      - portainer_data:/data:rw
    depends_on:
      - agent

volumes:
  portainer_data:
